###  REPLACING VALUES

In [3]:
import pandas as pd
import numpy as np
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [4]:
data.replace(-999.0,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [5]:
data.replace(-999.0,'a')

0       1
1       a
2       2
3       a
4   -1000
5       3
dtype: object

In [6]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [7]:
data.replace([-999.0,-1000.0],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [8]:
data.replace([-999.0,-1000.0],[100,200])

0      1.0
1    100.0
2      2.0
3    100.0
4    200.0
5      3.0
dtype: float64

In [9]:
data.replace({-999.0: 0.0 , -1000.0:1.0})

0    1.0
1    0.0
2    2.0
3    0.0
4    1.0
5    3.0
dtype: float64

In [10]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [25]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
       index=['Ohio', 'Colorado', 'New York'],
       columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [16]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [17]:
data.index = data.index.map(transform)

In [14]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [20]:
data = data.rename(index=str.title, columns=str.upper)

In [23]:
data

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [27]:
data.rename(index={'Ohio': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

### Discretization and Binning

In [49]:
# 2  ------- > 1-4
# 7 ----->   5-9
# pd.cut(single value , interval)

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
#(18,25]->0(code/index) , (25,35]->01 , (35,60]->02 , (60,100]->03

In [35]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [37]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [38]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [39]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [45]:
print("AGES :",ages)
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

# [18,26) , [26,36) , [36,61) , [61,100)

AGES : [18, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]


[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [47]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [50]:
print("AGES" , ages)
pd.cut(ages, bins, labels=group_names)


AGES [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]


[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [54]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020611    -0.042434    -0.035875     0.007129
std       0.960851     1.014489     0.995024     1.010001
min      -3.534886    -3.660267    -3.447027    -3.570363
25%      -0.635993    -0.698448    -0.740554    -0.702101
50%       0.010307    -0.045356    -0.052092    -0.005538
75%       0.586158     0.616017     0.641784     0.732510
max       2.937783     3.371288     2.750733     2.910959

In [57]:
col = data.head(10)
col

0         1         2         3
0  1.445263 -1.352192 -0.054655 -0.374374
1  1.670928  1.031838 -1.070853 -0.124553
2 -0.517364 -0.135927  0.891115  0.378766
3 -0.084962 -0.090141 -1.105122  0.179444
4 -0.762267  0.852333  0.147262 -1.831715
5 -0.169646 -0.698357  1.202543  0.388854
6 -1.143889  1.380534  0.174188 -0.351266
7 -0.531588  1.626461 -1.665098 -1.084318
8  0.333590 -0.557577  0.111434  0.379283
9 -0.086948  1.094720  1.718243 -0.416460

In [63]:
np.abs(col[np.abs(col) >= 1])

0         1         2         3
0  1.445263  1.352192       NaN       NaN
1  1.670928  1.031838  1.070853       NaN
2       NaN       NaN       NaN       NaN
3       NaN       NaN  1.105122       NaN
4       NaN       NaN       NaN  1.831715
5       NaN       NaN  1.202543       NaN
6  1.143889  1.380534       NaN       NaN
7       NaN  1.626461  1.665098  1.084318
8       NaN       NaN       NaN       NaN
9       NaN  1.094720  1.718243       NaN

In [65]:
col[col >= 1]

0         1         2   3
0  1.445263       NaN       NaN NaN
1  1.670928  1.031838       NaN NaN
2       NaN       NaN       NaN NaN
3       NaN       NaN       NaN NaN
4       NaN       NaN       NaN NaN
5       NaN       NaN  1.202543 NaN
6       NaN  1.380534       NaN NaN
7       NaN  1.626461       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN  1.094720  1.718243 NaN

In [83]:
col[(np.abs(col) >= 1).any(1)]

0         1         2         3
0  1.445263 -1.352192 -0.054655 -0.374374
1  1.670928  1.031838 -1.070853 -0.124553
3 -0.084962 -0.090141 -1.105122  0.179444
4 -0.762267  0.852333  0.147262 -1.831715
5 -0.169646 -0.698357  1.202543  0.388854
6 -1.143889  1.380534  0.174188 -0.351266
7 -0.531588  1.626461 -1.665098 -1.084318
9 -0.086948  1.094720  1.718243 -0.416460

In [86]:
np.sign(col)

0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1  1.0  1.0 -1.0 -1.0
2 -1.0 -1.0  1.0  1.0
3 -1.0 -1.0 -1.0  1.0
4 -1.0  1.0  1.0 -1.0
5 -1.0 -1.0  1.0  1.0
6 -1.0  1.0  1.0 -1.0
7 -1.0  1.0 -1.0 -1.0
8  1.0 -1.0  1.0  1.0
9 -1.0  1.0  1.0 -1.0

In [87]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [93]:
sampler = np.random.permutation(5)
sampler

array([1, 0, 3, 2, 4])

In [94]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [101]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
1   4   5   6   7

In [109]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [110]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [116]:
a = [1,2,3]
a.append(4)
a

[1, 2, 3, 4]

In [117]:
a.extend([4,5,6])
a

[1, 2, 3, 4, 4, 5, 6]

In [137]:
np.random.seed(12345)
values = np.random.rand(1)
values

array([0.92961609])

In [155]:
val = 'Presidential Initiative Artificial Intelligence Computing'
val

'Presidential Initiative Artificial Intelligence Computing'

In [156]:
val = val.split()
val

['Presidential', 'Initiative', 'Artificial', 'Intelligence', 'Computing']

In [157]:
print(val[0] + " " + val[1] + " " + val[2] + " " + val[3] + " " + val[4])

Presidential Initiative Artificial Intelligence Computing


In [158]:
" ".join(val)

'Presidential Initiative Artificial Intelligence Computing'

In [159]:
'Presidential' in val

True

In [180]:
val[0].index('d')

5

In [181]:
val[0].find('z')

-1

a  1   -0.967838
   2   -0.562257
   3    0.316160
b  1   -1.379198
   3    0.450554
c  1    0.092673
   2    1.248133
d  2    0.768101
   3    1.248804
dtype: float64

-0.5622566484317844